# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('R', '0002_auto_20171124_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='id_comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='R.Comentarios'),
        ),
    ]
