# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R', '0003_auto_20171124_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='imagen',
            field=models.ImageField(default='', upload_to='fotos_perfil'),
        ),
    ]
